#!/bin/bash
zone=us-east1-b

curl https://raw.githubusercontent.com/maprpartners/GCP/master/install.sh > /tmp/install_edge.sh

gcloud compute instances create --boot-disk-auto-delete --boot-disk-size=20GB --machine-type=n1-standard-4 --image=centos-7 --network=maprvpc --subnet=maprvpc --zone=${zone} --metadata-from-file startup-script=/tmp/install_edge.sh mapredge
sleep 10

subnet=`gcloud compute networks subnets list | grep us-east1 | grep maprvpc | awk '{print $4}'`

gcloud compute firewall-rules create allowmapredge --network maprvpc --allow tcp:22,tcp:9995 --source-ranges 0.0.0.0/0

gcloud compute instances add-tags mapredge --zone=${zone} --tags=allowmapredge
