#!/bin/bash

for i in {1..5}
do
#gcloud compute instances create --boot-disk-auto-delete --boot-disk-size=40GB --custom-cpu=4 --custom-memory=64GB --image=centos-7 --network=maprvpc --subnet=maprvpc --zone=us-east1-b --metadata-from-file startup-script=install.sh maprvm$i
gcloud compute instances create --boot-disk-auto-delete --boot-disk-size=40GB --machine-type=n1-standard-16 --image=centos-7 --network=maprvpc --subnet=maprvpc --zone=us-east1-b --metadata-from-file startup-script=install.sh maprvm$i
sleep 10
gcloud compute instances add-tags maprvm$i --zone=us-east1-b --tags=allowmapr
gcloud compute instances add-tags maprvm$i --zone=us-east1-b --tags=allowmaprint
done

#gcloud compute instances list

# create disks
for i in {1..5}
do
for j in {1..3}
do
gcloud compute disks create --type=pd-ssd --size=120GB --zone=us-east1-b maprvm$i-disk$j
done
done

# attach disks to a vm
for i in {1..5}
do
for j in {1..3}
do
gcloud compute instances  attach-disk maprvm$i --disk=maprvm$i-disk$j --zone=us-east1-b
done
done
