#!/bin/bash
zone=us-east1-b

curl https://raw.githubusercontent.com/maprpartners/GCP/master/install.sh > /tmp/install.sh
#wget https://raw.githubusercontent.com/maprpartners/GCP/master/install.sh -O /tmp/install.sh

for i in {1..5}
do
gcloud compute instances create --boot-disk-auto-delete --boot-disk-size=40GB --machine-type=n1-standard-16 --image=centos-7 --network=maprvpc --subnet=maprvpc --zone=${zone} --metadata-from-file startup-script=/tmp/install.sh maprvm$i
sleep 10
gcloud compute instances add-tags maprvm$i --zone=${zone} --tags=allowmapr
gcloud compute instances add-tags maprvm$i --zone=${zone} --tags=allowmaprint
done

#gcloud compute instances list

# create disks
for i in {1..5}
do
for j in {1..3}
do
gcloud compute disks create --type=pd-ssd --size=120GB --zone=${zone} maprvm$i-disk$j
done
done

# attach disks to the vms
for i in {1..5}
do
for j in {1..3}
do
gcloud compute instances  attach-disk maprvm$i --disk=maprvm$i-disk$j --zone=${zone}
done
done

gcloud compute instances list --zones=${zone}
